# Generated by Django 4.2 on 2025-11-02 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_duration', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, default='Spanish', max_length=40)),
                ('status', models.CharField(default='queued', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_file', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptionChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.IntegerField(blank=True, null=True)),
                ('end_time', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='queued', max_length=40)),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='api.transcription')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField(max_length=50)),
                ('url_link', models.TextField(max_length=100)),
                ('prompt', models.TextField(default='GENERE UN RESUMEN DE ACUERDO AL SIGUIENTE TEXTO:')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='api.transcription')),
            ],
        ),
    ]
