# Generated by Django 4.2 on 2025-11-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='audio_file',
            field=models.FileField(upload_to='audios/'),
        ),
    ]
