# Generated by Django 4.2 on 2025-11-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_transcription_audio_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcriptionchunk',
            options={'ordering': ['index']},
        ),
        migrations.AddField(
            model_name='transcriptionchunk',
            name='duration_sec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcriptionchunk',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='audios/chunks/'),
        ),
        migrations.AddField(
            model_name='transcriptionchunk',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transcriptionchunk',
            name='status',
            field=models.CharField(default='ready', max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='transcriptionchunk',
            unique_together={('transcription', 'index')},
        ),
    ]
