# Generated by Django 4.2 on 2025-11-02 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_transcriptionchunk_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionchunk',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transcriptionchunk',
            name='duration_sec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transcriptionchunk',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
    ]
