# Generated by Django 4.2 on 2025-11-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_transcriptionchunk_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionchunk',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
