# Generated by Django 4.2 on 2025-11-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_transcriptionchunk_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='temp_custom_prompt',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
